#include QMK_KEYBOARD_H

#define MAC_SIDE

#ifdef MAC_SIDE
#    include "keymap_german_mac_iso.h"
#else
#    include "keymap_german_linux.h"
#endif /* ifdef MAC_SIDE */

enum layers {
    _BONE = 0,
    _QWER,
    _COLE,
    _NUMS,
    _FUNC,
    _CTRL,
    _MSFX,
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {                                                                                                          //
    [_BONE] = LAYOUT_split_3x6_5(LALT_T(KC_BSPC), DE_J, DE_D, DE_U, DE_A, DE_X, DE_P, DE_H, DE_L, DE_M, DE_W, LALT_T(DE_SS),                                            //
                                 LCTL_T(KC_ESC), DE_C, DE_T, DE_I, DE_E, DE_O, DE_B, DE_N, DE_R, DE_S, DE_G, RCTL_T(DE_Q),                                              //
                                 LGUI_T(DE_LABK), DE_F, DE_V, DE_UDIA, DE_ADIA, DE_ODIA, KC_NO, KC_NO, KC_NO, KC_NO, DE_Y, DE_Z, KC_COMM, KC_DOT, DE_K, RGUI_T(KC_ENT), //
                                 KC_NO, MO(_MSFX), LT(_CTRL, KC_ENT), LSFT_T(KC_TAB), KC_NO, KC_NO, RSFT_T(KC_SPC), OSL(_NUMS), RALT_T(KC_APP), KC_MUTE),

    [_QWER] = LAYOUT_split_3x6_5(KC_TRNS, DE_Q, DE_W, DE_E, DE_R, DE_T, DE_Z, DE_U, DE_I, DE_O, DE_P, LALT_T(DE_UDIA),                           //
                                 KC_TRNS, DE_A, DE_S, DE_D, DE_F, DE_G, DE_H, DE_J, DE_K, DE_L, DE_ODIA, RCTL_T(DE_ADIA),                        //
                                 KC_TRNS, DE_Y, DE_X, DE_C, DE_V, DE_B, KC_NO, KC_NO, KC_NO, KC_NO, DE_N, DE_M, KC_COMM, KC_DOT, DE_SS, KC_TRNS, //
                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_COLE] = LAYOUT_split_3x6_5(KC_TRNS, DE_Q, DE_W, DE_F, DE_P, DE_B, DE_J, DE_L, DE_U, KC_TRNS, DE_ODIA, LALT_T(DE_UDIA),                     //
                                 KC_TRNS, DE_A, DE_R, DE_S, DE_T, DE_G, DE_M, DE_N, DE_E, DE_I, DE_O, RCTL_T(DE_ADIA),                           //
                                 KC_TRNS, DE_Z, DE_X, DE_C, DE_D, DE_V, KC_NO, KC_NO, KC_NO, KC_NO, DE_K, DE_H, KC_COMM, KC_DOT, DE_SS, KC_TRNS, //
                                 KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    [_NUMS] = LAYOUT_split_3x6_5(LALT_T(KC_DEL), DE_1, DE_2, DE_3, DE_4, DE_5, DE_6, DE_7, DE_8, DE_9, DE_0, LALT_T(DE_CIRC),                                                          //
                                 LCTL_T(KC_DOT), DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR, DE_AMPR, DE_LPRN, DE_RPRN, DE_AT, DE_COLN, RCTL_T(DE_PLUS),                              //
                                 LGUI_T(KC_COMM), DE_HASH, DE_DLR, DE_PIPE, DE_TILD, DE_EXLM, KC_NO, KC_NO, KC_NO, KC_NO, DE_EQL, DE_PERC, DE_DQUO, DE_QUOT, DE_UNDS, RGUI_T(DE_MINS), //
                                 KC_NO, QK_AREP, MO(_MSFX), QK_REP, KC_NO, KC_NO, KC_TRNS, OSL(_FUNC), KC_TRNS, KC_NO),

    [_FUNC] = LAYOUT_split_3x6_5(KC_LALT, KC_F1, KC_F2, KC_F3, KC_F4, DE_CENT, DE_PLMN, DE_LABK, DE_RABK, DE_COPY, DE_SECT, LALT_T(DE_ACUT),                       //
                                 KC_TRNS, KC_F5, KC_F6, KC_F7, KC_F8, DE_EURO, KC_PSCR, DE_LBRC, DE_RBRC, DE_REGD, DE_TM, KC_RCTL,                                 //
                                 KC_LGUI, KC_F9, KC_F10, KC_F11, KC_F12, DE_PND, KC_NO, KC_NO, KC_NO, KC_NO, DE_RDAQ, DE_LDAQ, DE_DLQU, DE_LDQU, DE_RDQU, KC_RGUI, //
                                 KC_NO, BRI_DN, MO(_MSFX), BRI_UP, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO),

    [_CTRL] = LAYOUT_split_3x6_5(OSM(MOD_LALT), KC_EJCT, KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, CG_NORM, DF(_BONE), DF(_QWER), DF(_COLE), CG_SWAP, QK_BOOT,                //
                                 OSM(MOD_LCTL), OSM(MOD_LSFT), OSM_SCG, OSM_SA, OSM(MOD_MEH), OSM(MOD_HYPR), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_DEL, EE_CLR,          //
                                 OSM(MOD_LGUI), OSM_SC, OSM_CA, OSM_CG, OSM_SG, OSM_AG, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_INS, CW_TOGG, //
                                 KC_NO, KC_APP, KC_NO, KC_TRNS, RGB_M_T, KC_NO, CW_TOGG, MO(_MSFX), KC_TRNS, KC_NO),

    [_MSFX] = LAYOUT_split_3x6_5(KC_LALT, KC_ACL2, KC_BTN4, KC_BTN5, RGB_M_P, RGB_M_B, RGB_TOG, RGB_VAI, RGB_HUI, RGB_SAI, RGB_MOD, KC_LALT,                             //
                                 KC_LCTL, KC_ACL0, KC_BTN3, KC_BTN2, KC_BTN1, RGB_M_R, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, RGB_M_SW, KC_RCTL,                            //
                                 KC_LGUI, KC_ACL1, KC_CUT, KC_COPY, KC_PSTE, RGB_M_K, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_U, KC_WH_D, KC_WH_R, RGB_M_SN, KC_RGUI, //
                                 KC_NO, KC_NO, KC_TRNS, KC_LSFT, KC_NO, KC_NO, KC_RSFT, KC_TRNS, OSM(KC_RALT), KC_NO)};

// #if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
// const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
//
// };
// #endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

#ifdef ENCODER_ENABLE
bool encoder_update_user(uint8_t index, bool clockwise) {
    switch (get_highest_layer(layer_state | default_layer_state)) {
        case _CTRL:
            // Page up/Page down
            if (clockwise) {
                tap_code(KC_RGHT);
            } else {
                tap_code(KC_LEFT);
            }
            break;
        case _NUMS:
            // Page up/Page down
            if (clockwise) {
                tap_code(KC_PGDN);
            } else {
                tap_code(KC_PGUP);
            }
            break;
        case _MSFX:
            // Brightness control
            if (clockwise) {
                tap_code(BRI_UP);
            } else {
                tap_code(BRI_DN);
            }
            break;
        default:
            // Volume control
            if (clockwise) {
                tap_code(KC_VOLU);
            } else {
                tap_code(KC_VOLD);
            }
    }
    return false;
}
#endif

#ifdef OLED_ENABLE
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_180;
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        // QMK Logo and version information
        // clang-format off
        static const char PROGMEM qmk_logo[] = {
            0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,0x90,0x91,0x92,0x93,0x94,
            0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xb0,0xb1,0xb2,0xb3,0xb4,
            0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,0xd0,0xd1,0xd2,0xd3,0xd4,0};
        // clang-format on

        oled_write_P(qmk_logo, false);
        oled_write_P(PSTR("Kyria rev1.0     "), false);
#    ifdef MAC_SIDE
        oled_write_P(PSTR("\n    struckmb@MAC    "), true);
#    else
        oled_write_P(PSTR("\n  struckmb@LIN/WIN  "), true);
#    endif /* ifdef MAC_SIDE */

        // Host Keyboard Layer Status
        oled_write_P(PSTR("\n\nLayer: "), false);
        switch (get_highest_layer(layer_state | default_layer_state)) {
            case _BONE:
                oled_write_P(PSTR("Bone        "), false);
                break;
            case _QWER:
                oled_write_P(PSTR("QWERTY      "), false);
                break;
            case _COLE:
                oled_write_P(PSTR("Colemak-DH  "), false);
                break;
            case _NUMS:
                oled_write_P(PSTR("Num/Sym     "), false);
                break;
            case _FUNC:
                oled_write_P(PSTR("Fn/Sym      "), false);
                break;
            case _CTRL:
                oled_write_P(PSTR("Ctrl/Nav    "), false);
                break;
            case _MSFX:
                oled_write_P(PSTR("Mouse/FX    "), false);
                break;
            default:
                oled_write_P(PSTR("Undefined   "), false);
        }

        // determin if ctl/gui keys are swapped
        keymap_config.raw = eeconfig_read_keymap();
        if (keymap_config.swap_lctl_lgui || keymap_config.swap_rctl_rgui) {
            oled_write_P(PSTR("S"), true);
        } else {
            oled_write_P(PSTR(" "), false);
        }

        // Write host Keyboard LED Status to OLEDs
        // led_t led_usb_state = host_keyboard_led_state();
        // oled_write_P(led_usb_state.num_lock ? PSTR("NUMLCK ") : PSTR("       "), false);
        // oled_write_P(led_usb_state.caps_lock ? PSTR("CAPLCK ") : PSTR("       "), false);
        // oled_write_P(led_usb_state.scroll_lock ? PSTR("SCRLCK ") : PSTR("       "), false);
    } else {
        // clang-format off
        static const char PROGMEM kyria_logo[] = {
            0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128,128,192,224,240,112,120, 56, 60, 28, 30, 14, 14, 14,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 14, 14, 14, 30, 28, 60, 56,120,112,240,224,192,128,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,192,224,240,124, 62, 31, 15,  7,  3,  1,128,192,224,240,120, 56, 60, 28, 30, 14, 14,  7,  7,135,231,127, 31,255,255, 31,127,231,135,  7,  7, 14, 14, 30, 28, 60, 56,120,240,224,192,128,  1,  3,  7, 15, 31, 62,124,240,224,192,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,240,252,255, 31,  7,  1,  0,  0,192,240,252,254,255,247,243,177,176, 48, 48, 48, 48, 48, 48, 48,120,254,135,  1,  0,  0,255,255,  0,  0,  1,135,254,120, 48, 48, 48, 48, 48, 48, 48,176,177,243,247,255,254,252,240,192,  0,  0,  1,  7, 31,255,252,240,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,255,255,255,  0,  0,  0,  0,  0,254,255,255,  1,  1,  7, 30,120,225,129,131,131,134,134,140,140,152,152,177,183,254,248,224,255,255,224,248,254,183,177,152,152,140,140,134,134,131,131,129,225,120, 30,  7,  1,  1,255,255,254,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0,255,255,  0,  0,192,192, 48, 48,  0,  0,240,240,  0,  0,  0,  0,  0,  0,240,240,  0,  0,240,240,192,192, 48, 48, 48, 48,192,192,  0,  0, 48, 48,243,243,  0,  0,  0,  0,  0,  0, 48, 48, 48, 48, 48, 48,192,192,  0,  0,  0,  0,  0,
            0,  0,  0,255,255,255,  0,  0,  0,  0,  0,127,255,255,128,128,224,120, 30,135,129,193,193, 97, 97, 49, 49, 25, 25,141,237,127, 31,  7,255,255,  7, 31,127,237,141, 25, 25, 49, 49, 97, 97,193,193,129,135, 30,120,224,128,128,255,255,127,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0, 63, 63,  3,  3, 12, 12, 48, 48,  0,  0,  0,  0, 51, 51, 51, 51, 51, 51, 15, 15,  0,  0, 63, 63,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 48, 48, 63, 63, 48, 48,  0,  0, 12, 12, 51, 51, 51, 51, 51, 51, 63, 63,  0,  0,  0,  0,  0,
            0,  0,  0,  0, 15, 63,255,248,224,128,  0,  0,  3, 15, 63,127,255,239,207,141, 13, 12, 12, 12, 12, 12, 12, 12, 30,127,225,128,  0,  0,255,255,  0,  0,128,225,127, 30, 12, 12, 12, 12, 12, 12, 12, 13,141,207,239,255,127, 63, 15,  3,  0,  0,128,224,248,255, 63, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  3,  7, 15, 62,124,248,240,224,192,128,  1,  3,  7, 15, 30, 28, 60, 56,120,112,112,224,224,225,231,254,248,255,255,248,254,231,225,224,224,112,112,120, 56, 60, 28, 30, 15,  7,  3,  1,128,192,224,240,248,124, 62, 15,  7,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  3,  7, 15, 14, 30, 28, 60, 56,120,112,112,112,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,112,112,112,120, 56, 60, 28, 30, 14, 15,  7,  3,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
        };
        // clang-format on
        oled_write_raw_P(kyria_logo, sizeof(kyria_logo));
    }
    return false;
}
#endif
